//const BASE_URL: string = "/CameleerBook/"
export const HOME: string = "/"
export const CHAPTER: string = "/chapter"
export const GALLERY: string = "/gallery"
export const RELATED_WORK: string = "/relatedwork"
export const ABOUT: string = "/about"